export const SOCCERINFO = [
    {
        id:0,
        name: '3 Year Old Division',
        description:'3 Year old Soccer is to introduce kids to the game. Play is five versus five without a goalkeeper with a reduced field and goal size. One coach will be allowed on the field for each team to help guide players. Older 2 year olds are welcome to play.',
        rules:['Coed: Girls & Boys',
        'Ball Size: Size Three (3)',
        'Field Size: Approximately 15 yards x 20 yards',
        'Goal Size: 4’ Height x 6’ Wide',
        'Game: Four Quarters, Six Minutes each',
        'Coaches are Parent Volunteers'],
        equipment:['Shin Guards', 'Soccer Ball'],
        registration:['League dues for season', 'Game fields', 'Game equipment', 'Field staff', 'Liability insurance with a medical rider', 'Game jersey', 'League administration' ],
        image:'/assets/images/soccer_3yo_division.jpg'
    },
    {
        id:1,
        name: '5U Division',
        description:'For ages 5 and under soccer division is aimed towards those in their first few seasons of the sport. There is no goalkeeper in this division and is played six versus six with a reduced field and goal size. One coach will be allowed on the field for each team to help guide players!',
        rules:['Coed: Girls & Boys',
        'Ball Size: Size Three (3)',
        'Field Size: Approximately 15 yards x 30 yards',
        'Goal Size: 4’ Height x 6’ Wide',
        'Game: Four Quarters, Eight Minutes each',
        'Coaches are Parent Volunteers'],
        equipment:['Shin Guards', 'Soccer Ball'],
        registration:['League dues for season', 'Game fields', 'Game equipment', 'Field staff', 'Liability insurance with a medical rider', 'Game jersey', 'League administration' ],
        image:'/assets/images/soccer_5u_division.jpg'
    },
    {
        id:2,
        name: '7U Division',
        description:'Our ages 7 and under soccer division is aimed towards those with little experience in the sport. At this age group, we introduce goalkeepers, a larger field and goal size, while also increasing the amount of players to cover the space (eight versus eight with a goalkeeper). Rule set becomes more advanced over our 3 and 5U levels as well. One coach will still be allowed on the field for each team to help guide players!',
        rules:['Coed: Girls & Boys',
        'Ball Size: Size Four (4)',
        'Field Size: Approximately 35 yards x 60 yards',
        'Goal Size: 6’ Height x 8’ Wide',
        'Game: Four Quarters, Ten Minutes each',
        'Coaches are Parent Volunteers'],
        equipment:['Shin Guards', 'Soccer Ball'],
        registration:['League dues for season', 'Game fields', 'Game equipment', 'Field staff', 'Liability insurance with a medical rider', 'Game jersey', 'League administration' ],
        image:'/assets/images/soccer_7u_division.jpg'   
    },
    {
        id:3,
        name: '9U Division',
        description:'Our 9U Soccer division is aimed towards those with some experience in the sport. At this age group, we introduce a larger field and goal size and more specific rule set. Offside penalty and Cards become utilized in this division, as well as penalty kicks. Games are still played eight on eight with a goalkeeper, but coaches are no longer allowed on the field of play.',
        rules:['Coed: Girls & Boys',
        'Ball Size: Size Four (4)',
        'Field Size: Approximately 40 yards x 70 yards',
        'Goal Size: 7’ Height x 14’ Wide',
        'Game: Two Halves, Twenty Minutes each',
        'Coaches are Parent Volunteers'],
        equipment:['Shin Guards', 'Soccer Ball', 'Soccer Cleats'],
        registration:['League dues for season', 'Game fields', 'Game equipment', 'Field staff', 'Liability insurance with a medical rider', 'Game jersey', 'League administration' ],
        image:'/assets/images/soccer_9u_division.jpg' 
    },
    {
        id:4,
        name: '11U Division',
        description:'Our 11U Soccer division is aimed towards those with some experience in the sport. At this age group, we begin using the official size Soccer ball while also increasing the game time. Rule set becomes more specific to FIFA rules. Games are played eight versus eight including a goalkeeper. This division can sometimes require light travel to sites in Henderson, Las Vegas, and North Las Vegas for games.',
        rules:['Coed: Girls & Boys',
        'Ball Size: Size Four (4)',
        'Field Size: Approximately 40 yards x 70 yards',
        'Goal Size: 7’ Height x 14’ Wide',
        'Game: Two Halves, Twenty-Five Minutes each',
        'Coaches are Parent Volunteers'],
        equipment:['Shin Guards', 'Soccer Ball', 'Soccer Cleats'],
        registration:['League dues for season', 'Game fields', 'Game equipment', 'Field staff', 'Liability insurance with a medical rider', 'Game jersey', 'League administration' ],
        image:'/assets/images/soccer_11u_division.jpg' 
    },
    {
        id:5,
        name: '15U Division',
        description:'Our 15U Soccer division is aimed towards those with experience in the sport or ambitions to play in High School. Games are played on official size fields (or close) with 11 players on each team on the field. High school rules are enforced and the game time is extended over previous divisions.  This division can involve travel to fields throughout the valley.',
        rules:['Coed: Girls & Boys',
        'Ball Size: Size Four (5)',
        'Field Size: Approximately 40 yards x 100 yards',
        'Goal Size: 7’ Height x 14’ Wide',
        'Game: Two Halves, Twenty-Five Minutes each',
        'Coaches are Parent Volunteers'],
        equipment:['Shin Guards', 'Soccer Ball', 'Soccer Cleats'],
        registration:['League dues for season', 'Game fields', 'Game equipment', 'Field staff', 'Liability insurance with a medical rider', 'Game jersey', 'League administration' ],
        image:'/assets/images/soccer_15u_division.jpg' 
    }
]